### PR TITLE
fixing service selection

### LINKED ISSUE #1844: bug(ui): observability/logs no longer lets you select a service
**Describe the bug**
After we replaced SRQL this functionality stopped working, you should see a list of known services that you can select and filter by when viewing logs.

**To Reproduce**

1. Go to 'Observability'
2. Click on 'Service' dropdown
3. Missing services, just says 'All'

**Expected behavior**

Since the `serviceradar-core` is already basically collecting a list of services that have reported into it (flush.go / flushServices), we should be able to read from that list and then populate the web ui drop-down, then users can filter by services and we don't have to parse raw data to figure that all out.

We need to do this through /api/query, this should already be supported since we have "in:services" defined in the SRQL system.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mfreeman451**
## IMPORTANT: Please sign the Developer Certificate of Origin

Thank you for your contribution to ServiceRadar. Please note, when contributing, the developer must include
a [DCO sign-off statement]( https://developercertificate.org/) indicating the DCO acceptance in one commit message. Here
is an example DCO Signed-off-by line in a commit message:

```
Signed-off-by: J. Doe <j.doe@domain.com>
```

## Code checklist before requesting a review

- [ ] I have signed the DCO?
- [ ] The build completes without errors?
- [ ] All tests are passing when running make test?

### CODE REVIEW

File: web/src/utils/logServiceOptions.ts [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+    'sync': 'serviceradar-sync',
+    'flowgger': 'serviceradar-flowgger',
+    'zen': 'serviceradar-zen',
+    'network_sweep': 'serviceradar-network-sweep',
+    'kv': 'serviceradar-datasvc',
+    'rperf-checker': 'serviceradar-rperf-checker',
+    'mapper': 'serviceradar-mapper',
+    'serviceradar-agent': 'serviceradar-agent',
+    'ping': 'serviceradar-ping',
+    'ssh': 'serviceradar-ssh',
```
Comment (mfreeman451) [inline web/src/utils/logServiceOptions.ts]: ssh should just map to the agent

File: web/src/utils/logServiceOptions.ts [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+    'core': 'serviceradar-core',
+    'sync': 'serviceradar-sync',
+    'flowgger': 'serviceradar-flowgger',
+    'zen': 'serviceradar-zen',
+    'network_sweep': 'serviceradar-network-sweep',
+    'kv': 'serviceradar-datasvc',
+    'rperf-checker': 'serviceradar-rperf-checker',
+    'mapper': 'serviceradar-mapper',
+    'serviceradar-agent': 'serviceradar-agent',
+    'ping': 'serviceradar-ping',
```
Comment (mfreeman451) [inline web/src/utils/logServiceOptions.ts]: ping should map to the agent

**Review by mfreeman451 — COMMENTED** [review]
lgtm
