### PR TITLE
fix: agent updated to respect sweep interval

### LINKED ISSUE #2646: bug: scanning/sweep interval is being ignored
**Describe the bug**

I have set the sweep interval for the only sweep profile in the system to 6 hours, still getting scans every 5 minutes from the `dusk-agent`.

Image

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mfreeman451**
## IMPORTANT: Please sign the Developer Certificate of Origin

Thank you for your contribution to ServiceRadar. Please note, when contributing, the developer must include
a [DCO sign-off statement]( https://developercertificate.org/) indicating the DCO acceptance in one commit message. Here
is an example DCO Signed-off-by line in a commit message:

```
Signed-off-by: J. Doe <j.doe@domain.com>
```

## Code checklist before requesting a review

- [ ] I have signed the DCO?
- [ ] The build completes without errors?
- [ ] All tests are passing when running make test?

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fixed sweep interval configuration being ignored by agent

- Refactored gateway sweep config parsing to merge multiple groups

- Added ticker reset mechanism to respect interval changes at runtime

- Implemented deduplication logic for ports, modes, and networks

- Added comprehensive specification and task documentation

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Multiple Sweep Groups"] -->|"Merge with dedup"| B["Single SweepConfig"]
  B -->|"Parse interval"| C["Sweep Service"]
  C -->|"Update config"| D["NetworkSweeper"]
  D -->|"Detect interval change"| E["Reset Ticker"]
  E -->|"Apply new interval"| F["Respect configured sweep cycle"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>sweep_config_gateway.go</strong><dd><code>Merge multiple sweep groups with deduplication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/agent/sweep_config_gateway.go

<ul><li>Changed from using only first group to merging all sweep groups<br> <li> Added deduplication maps for ports, modes, and networks<br> <li> Implemented merge logic that combines targets while avoiding <br>duplicates<br> <li> Uses shortest interval when multiple groups have different intervals<br> <li> Uses highest concurrency and timeout values across groups</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-0590118d93b1be7997233109d892bea154ed59038b8069290db99dc03080d307">+60/-25</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>sweeper.go</strong><dd><code>Implement ticker reset on interval changes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sweeper/sweeper.go

<ul><li>Added <code>tickerReset</code> channel to signal interval changes<br> <li> Implemented case handler in Start loop to detect and reset ticker<br> <li> Modified UpdateConfig to detect interval changes and signal reset<br> <li> Logs interval changes with new duration for debugging</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-d11dee1504de681453c5a04e22ae44d64820221ac6b84a1630d3a3929dace47a">+17/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>sweep_service.go</strong><dd><code>Add logging for sweep config updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/agent/sweep_service.go

<ul><li>Added logging to display the new interval being applied<br> <li> Logs sweep group ID for better debugging and traceability</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-988114dc491154ea9a249227411b24e463212831cd81b43e0844862ce7a41343">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>proposal.md</strong><dd><code>Add proposal for sweep interval fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

openspec/changes/fix-sweep-interval-config/proposal.md

<ul><li>Documents the issue where configured sweep intervals are ignored<br> <li> Specifies requirements for interval propagation from Profile to Agent<br> <li> Defines behavior for conflicting intervals across multiple sweep jobs<br> <li> Identifies affected specs and code components</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-f27ffaf5ee9afa6dd25505556d0db3ccac076b59730e2ff03d02d68130efb20c">+13/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>spec.md</strong><dd><code>Define sweep job configuration specifications</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

openspec/changes/fix-sweep-interval-config/specs/sweep-jobs/spec.md

<ul><li>Defines requirement for sweep job compiled config output format<br> <li> Specifies custom interval propagation scenario with 6-hour example<br> <li> Documents device query evaluation at compile time<br> <li> Defines merge behavior for multiple sweep jobs with interval selection<br> <li> Specifies agent parsing of device targets with TCP ports<br> <li> Documents port preservation for device-targeted sweeps<br> <li> Defines TCP mode port requirement validation</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-735b9b6d278ca31f4490b6370265c2be02454766daa41b68beb1591ed7bc42c4">+61/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>tasks.md</strong><dd><code>Add implementation tasks for sweep interval fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

openspec/changes/fix-sweep-interval-config/tasks.md

<ul><li>Lists core service updates needed for interval field population<br> <li> Specifies agent verification tasks for reading and respecting <br>intervals<br> <li> Includes validation tasks for end-to-end interval configuration</ul>

</details>

  </td>
  <td><a href="https://github.com/carverauto/serviceradar/pull/2673/files#diff-89a9bebff3ea9752ca25b5cb5d00c25ee9a8abcccc5392642f8fd7dc4c1782e9">+12/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tbody></table>

</details>

___

### CODE REVIEW

File: pkg/agent/push_loop.go [hunk 1]
```diff
@@ -800,12 +800,12 @@ func (p *PushLoop) pushSysmonStatus(ctx context.Context, status *proto.GatewaySe
...
 				// Append a new chunk for each sample.
 				chunks = append(chunks, &proto.GatewayStatusChunk{
-					Services:    []*proto.GatewayServiceStatus{s},
-					GatewayId:   "",
-					AgentId:     agentID,
-					Timestamp:   time.Now().UnixNano(),
-					Partition:   partition,
-					SourceIp:    p.getSourceIP(),
+					Services:  []*proto.GatewayServiceStatus{s},
+					GatewayId: "",
```
Comment (mfreeman451) [inline pkg/agent/push_loop.go]: seems like we should be able to set this

File: pkg/agent/sync_runtime.go [hunk 2]
```diff
@@ -380,7 +380,7 @@ func (r *SyncRuntime) buildResultsStatusChunks(
 	agentID := r.server.config.AgentID
 	partition := r.server.config.Partition
 	r.server.mu.RUnlock()
-	return buildResultsStatusChunksForAgent(chunks, serviceName, serviceType, agentID, partition)
+	return buildResultsStatusChunksForAgent(chunks, serviceName, serviceType, agentID, partition, "")
```
Comment (mfreeman451) [inline pkg/agent/sync_runtime.go]: ??

**Review by mfreeman451 — COMMENTED** [review]
lgtm
