### PR TITLE
2618 bug not capturing response time from sweep results

### LINKED ISSUE #2618: bug: not capturing response time from sweep results
**Describe the bug**
We should see response time (in ms) in these sweep results but it seems to be missing:

Image

Image

This might be related to the device flapping issue #2381 as you can see in the 2nd screenshot, we get some results with ms some without, seems to coincide with the flapping issues we see on other devices, except those ones are showing as unavailable:

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mfreeman451**
## IMPORTANT: Please sign the Developer Certificate of Origin

Thank you for your contribution to ServiceRadar. Please note, when contributing, the developer must include
a [DCO sign-off statement]( https://developercertificate.org/) indicating the DCO acceptance in one commit message. Here
is an example DCO Signed-off-by line in a commit message:

```
Signed-off-by: J. Doe <j.doe@domain.com>
```

## Code checklist before requesting a review

- [ ] I have signed the DCO?
- [ ] The build completes without errors?
- [ ] All tests are passing when running make test?

### CODE REVIEW

File: elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex [hunk 1]
```diff
@@ -54,9 +54,10 @@ defmodule ServiceRadar.AgentConfig.Compilers.SweepCompiler do
   def compile(partition, agent_id, opts \\ []) do
     # DB connection's search_path determines the schema
     actor = opts[:actor] || SystemActor.system(:sweep_compiler)
+    gateway_id = opts[:gateway_id]
 
-    # Load sweep groups for this partition/agent
-    groups = load_sweep_groups(partition, agent_id, actor)
+    # Load sweep groups for this partition/agent/gateway
+    groups = load_sweep_groups(partition, agent_id, gateway_id, actor)
```
Comment (mfreeman451) [inline elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex]: shouldnt be looking at agent gateway id anymore

File: elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex [hunk 2]
```diff
@@ -126,13 +127,17 @@ defmodule ServiceRadar.AgentConfig.Compilers.SweepCompiler do
     |> String.slice(0, 16)
   end
 
-  defp load_sweep_groups(partition, agent_id, actor) do
+  defp load_sweep_groups(partition, agent_id, gateway_id, actor) do
```
Comment (mfreeman451) [inline elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex]: same thing here

File: elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex [hunk 3]
```diff
@@ -126,13 +127,17 @@ defmodule ServiceRadar.AgentConfig.Compilers.SweepCompiler do
...
-      |> Ash.Query.for_read(:for_agent_partition, %{partition: partition, agent_id: agent_id})
+      |> Ash.Query.for_read(:for_agent_partition, %{
+        partition: partition,
+        agent_id: agent_id,
+        gateway_id: gateway_id
+      })
 
     Logger.debug(
-      "SweepCompiler: loading groups for partition=#{inspect(partition)}, agent_id=#{inspect(agent_id)}"
+      "SweepCompiler: loading groups for partition=#{inspect(partition)}, agent_id=#{inspect(agent_id)}, gateway_id=#{inspect(gateway_id)}"
```
Comment (mfreeman451) [inline elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex]: dont need gw id

File: elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex [hunk 4]
```diff
@@ -143,7 +148,7 @@ defmodule ServiceRadar.AgentConfig.Compilers.SweepCompiler do
 
         Enum.each(groups, fn g ->
           Logger.debug(
-            "SweepCompiler: group #{g.name} - target_query=#{inspect(g.target_query)}, static_targets=#{inspect(g.static_targets)}"
+            "SweepCompiler: group #{g.name} - target_query=#{inspect(g.target_query)}, static_targets=#{inspect(g.static_targets)}, gateway_id=#{inspect(g.gateway_id)}"
```
Comment (mfreeman451) [inline elixir/serviceradar_core/lib/serviceradar/agent_config/compilers/sweep_compiler.ex]: -gw id

**Review by mfreeman451 — COMMENTED** [review]
lgtm
